### ISSUE TITLE
data structure in samples

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-v-grid#12]
Having had a fresh look at the "basic use" sample I noticed that I see how to define columns and set the attributes of these columns. What is not described explicitly is that these attributes are actually properties of the underlying data of the grid (btw. would renaming them to `properties` make sense?).

It would be helpful if we had a single example of a data record. Not sure where to put this. Here are some possible places I can imagine that:

* instead of or in addition to the form on the right of the grid - I imagine a formatted JSON representation of the row currently selected
* as an additional tab in code preview - downside of this is the users have to click on it and it would be very convenient to see it from the start as to immediately grasp the connection between properties and columns

I think the first would actually look nice. :smile:

**Comment by vegarringdal** [comment]
**Dataview/json view:**
-yes that would be nice, could have a tab for the detail view part

**attribute**
Been so used to using word "attribute" I never really though about it.
Its really just the ````attribute="name``` that have the value that gets binded, not all.
Maybe renaming ```value-attribute="name``` would be more explaining, but then its more to write
For rows its the value that gets put into value.bind="xx", th grid adds rowRef if its missing, didnt want to force user to write it so its simpler to use.

**Comment by Thanood** [comment]
When I read "attribute" I think of HTML. Maybe just my reflexes. :smile: 
What's the "real" name of
```json
{
  "id": 0,
  "title: "my object"     <--- this
}
```

I would prefer a widely adopted name there.
What about `field`?

**Comment by vegarringdal** [comment]
yes, field is more correct I think.
How this would look when used:

simple:
```html
col-field="name"
```

More advanced
```
col-field="number | numberFormat & updateTrigger:'blur':'paste'"
```

Maybe rename some of the others too while we are at it
since these are only used inside v-grid-col that is only a configuration element,I dont see the need for "v-" prefix here like I have on the custom attibutes

---

```
//from
sort="name"

//to
col-sort-field="name"
```
---

```
from
`filter="name|*|onKeyDown"

//to
col-filter-field="name|*|onKeyDown"
```

---

```
//from
attributeFilter: "v-header-menu='date'",
attributeRow: "v-row-menu='date'"
attributeLabel: "v-sort:'name'"

//to
col-add-filter-attributes: "v-header-menu='date'",
col-add-row-attributes: "v-row-menu='date'"
col-add-label-attributes: "my-own-attribute='x'"
```

---

```
//from
`width="100"

//to
col-width="100"
```

---

```
//from
`css="color:${tempRef.numberColor};font-weight:${tempRef.numberFont}"

//to
col-css="color:${tempRef.numberColor};font-weight:${tempRef.numberFont}"
```

---

```
//from
header="Name"

//to
col-header-name="Name"
```

--

```
//from
type="Name"

//to
col-type="Name"
```

**Comment by vegarringdal** [comment]
Closing this for now, col names changed.
Can have a look at the json view later, feel free to create a own issue for that one if you feel its very important
