### ISSUE TITLE
change package name to aurelia-v-grid

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-v-grid#13]
At the moment this package is still called `skeleton-bridge` in package.json and sample/src/main.js.

https://github.com/aurelia-ui-toolkits/aurelia-v-grid/blob/master/package.json#L2
https://github.com/aurelia-ui-toolkits/aurelia-v-grid/blob/master/sample/src/main.js#L7

We should rename it to the actual name of this project. :smile: 
Also should be part of #5

**Comment by vegarringdal** [comment]
fixed

**Comment by Thanood** [comment]
:+1:
