### ISSUE TITLE
Start the book that documents the process of building v-grid

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-v-grid#2]

**Comment by adriatic** [comment]
See **[this book](https://www.gitbook.com/book/aurelia-ui-toolkits/building-a-new-bridge/details)**

![image](https://cloud.githubusercontent.com/assets/2712405/15630386/b13463bc-2506-11e6-9391-f29d0796256a.png)

**Comment by vegarringdal** [comment]
Closing this for now
