### ISSUE TITLE
Comments on gui

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-v-grid#22]

**Comment by vegarringdal** [comment]
Info, have a live sample running here btw, nice to know about so you dont have to install everything on the slow mac :smile: 
http://vegarringdal.github.io/vGrid/

**Comment by vegarringdal** [comment]
**Progress so far:**

Temp GitBook:[link](https://vegarringdal.gitbooks.io/v-grid-dev/content/) (thx to @Thanood  here)

Temp live demo of sample app [link](http://vegarringdal.github.io/vGrid/)

Gist.run samples of 3 ways to make it:
- [simple column html](https://gist.run/?id=fbd4e9f36d5eacd120dfac8184601f8d)
- [column.bind](https://gist.run/?id=a3f31efc2caf188cacf0e68e37dc4a22)
- [custom html](https://gist.run/?id=6ad85edc11f552f2afde0bf19bf14333)

**Comment by vegarringdal** [comment]
Dont see the need for this to be open anymore, feel free to reopen it again/create new issue is you see anything
