### ISSUE TITLE
add readonly property to v-grid-col (when no row template is used)

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-v-grid#39]
Being able to use row templates and use the default (shown below) is very powerful. Would it be possible to make a `v-grid-col` readonly without having to supply a row template?

`<v-grid-col col-width="300" col-header-name="Name" col-field="package" col-sort="package" col-filter="package|*|onKeyDown"></v-grid-col>`

**Comment by vegarringdal** [comment]
By using the "**col-add-row-attributes**" ```col-add-row-attributes="readonly"```
This with this attribute the sting you put in it gets added to row, here you can use custom attribute etc tec, just have space between them if you add more then 1
