### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-v-grid#4]
Structure and notes about this catalog..

:point_up: [2. Juni 2016 21:34](https://gitter.im/aurelia-ui-toolkits/team?at=57508a33ec10ddbb09dd3bbf)

![image](https://cloud.githubusercontent.com/assets/677826/15758657/e41c9d0e-290b-11e6-881c-fac483fc5303.png)

![image](https://cloud.githubusercontent.com/assets/677826/15758665/e889e0f4-290b-11e6-913b-426d4ba6bf68.png)

**Comment by Thanood** [comment]
The nav item `Catalog index`/`Project status` doesn't really make sense, right?

**Comment by adriatic** [comment]
Most certainly does not, just like Components Catalog. Aurelia-v-grid is really a v-grid plugin (just like any other aurelia framework plugin) and the related catalog app is a collection of articles describing the v-grid use.
