### ISSUE TITLE
opt-in or opt-out of contextmenu

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-v-grid#40]
![image](https://cloud.githubusercontent.com/assets/2189477/16706604/16d43914-45b3-11e6-8dc8-71f9157b9bb3.png)

could you add an option so the context menu can be either enabled or disabled? in monterey we have the project list that doesn't need a context menu

**Comment by JeroenVinke** [comment]
wait is this `v-row-menu="index" ` ?

**Comment by vegarringdal** [comment]
```v-row-menu``` thats the attibute activating the grid yes, need to remove that if you are using it, if the grid still shows a menu then I have a bug

**Comment by JeroenVinke** [comment]
ah, is `v-context-menu` a better name maybe?

**Comment by vegarringdal** [comment]
Yes, maybe, atm there is ```v-row-menu``` and ```v-header-menu``` one if for the header for editing filters, on is simpel row-menu for copy/paste.
Trying to be careful about editing some of the names since some users have the grid in production

**Comment by vegarringdal** [comment]
Guessing you copied the gist samples since you ended up with the row.menu in you grid :-)
