### ISSUE TITLE
get selection

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia-ui-toolkits/aurelia-v-grid#41]
how do I know which rows are selected? http://aurelia-ui-toolkits.github.io/demo-v-grid/#/documentation

**Comment by vegarringdal** [comment]
https://aurelia-ui-toolkits.gitbooks.io/aurelia-v-grid-docs/content/chap06/#same-as-above-just-in-binded-collection

```getSelectedRowsMain()```

**Comment by JeroenVinke** [comment]
i'd document it [here](https://aurelia-ui-toolkits.gitbooks.io/aurelia-v-grid-docs/content/chap04/v-selection.html) too because that's were I looked to find everything I needed to add checkboxes and get the selected items

**Comment by vegarringdal** [comment]
If you see things that confuse you/missing please post issue in the book to like this, very helpful.


![image](https://cloud.githubusercontent.com/assets/2901416/16707584/2e2f1a4a-45d4-11e6-89f1-a2a612d96268.png)

**Comment by vegarringdal** [comment]
Added link to selection function under the "v-selection" attribute
