### ISSUE TITLE
prevent using !important in styles

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-v-grid#53]
Can you try not to use `!important` here?
https://github.com/aurelia-ui-toolkits/aurelia-v-grid/blob/master/src/vGrid/styles/v-grid.css#L84-L100

It's hard to override this.. 😃 
(tried it here: https://github.com/monterey-framework/monterey/pull/304)

**Comment by vegarringdal** [comment]
Ill have a look in the end of the week, might have been a reason why Im using it, but I also have option to replace some class names earlier, that might be somethink I should consider again.

this is what I need to be able to edit as a option:
https://github.com/aurelia-ui-toolkits/aurelia-v-grid/blob/master/src/vGrid/v-grid-config.js#L26
And check that my rebuild didnt bring back any hardcoded css classes :-)

**Comment by Thanood** [comment]
I can probably help with the styles, depending on time constraints. 😃

**Comment by vegarringdal** [comment]
Did this fix, hopefully Ill get time to see what you guys have done in monterey later this week
Tell me how it goes
