### ISSUE TITLE
sample/src/shared/markdown.js has "excessive" run_pretty import

### ISSUE THREAD

**Issue by mingqin1** [aurelia-ui-toolkits/aurelia-v-grid#59]
Hi:
  I commented out following line " import 'google/code-prettify/loader/run_prettify" . Sample codes are working fine. 
 If you are fine with getting rid of this import, should package.json's  line (
"google/code-prettify": "github:google/code-prettify@master")  be moved away as well?

**Comment by vegarringdal** [comment]
thx, Ill try and have a look at it when I get time, since its not a bug in the grid I will prioritize new features Im playing around with.
