### ISSUE TITLE
Problem with scandic characters. 

### ISSUE THREAD

**Issue by JOKaija** [aurelia-ui-toolkits/aurelia-v-grid#61]
Uncaught (in promise) Error: Lexer Error: Unexpected character [�] at column in expression 

One column includes "ä" character....

{colField:"Tuote läh. pvm."},

And v-grid halts...

**Comment by Thanood** [comment]
`colField` takes a Javascript expression. I'm not sure if special characters can be used in JS expressions (actually never tried it). I'm pretty sure you cannot use spaces, though. 😏 

Is it possible you wanted to do something like this?

```javascript
{colField: "actualFieldName", colHeaderName:"Tuote läh. pvm."},
```

**Comment by JOKaija** [comment]
Stupid me... I can't use non-json compatible strings for colField... ok, that is clear... thanks!

Ok, this colHeaderName wont halt v-grid, but now the problem is, that it shows diamond instead of "ä" character...

od, since I use UTF8 for whole aurelia + visual system...

**Comment by vegarringdal** [comment]
Is this a issue in header only, or in the rows too?
Maybe bootstrap font manages to mess it up (really dont know atm)

**Comment by JOKaija** [comment]
It is also rows too...

**Comment by Thanood** [comment]
Strange, I'm using German language values here which also has some special characters (including ä) and it works for me.

**Comment by JOKaija** [comment]
More info:

If I write äö characters to column / rof definitions on editor, they will show as diamonds. BUT when
row-data is taken from database, all äö characters are just fine... :-)

**Comment by Thanood** [comment]
That really sounds like an encoding issue.
The thing is.. Anything (any file) can change encoding, even responses from services. I'd bet on something "disturbing" your UTF8 setup. Had that encoding nightmare often enough at work. 😃

**Comment by JOKaija** [comment]
Seems, it has to do something with 4.6.2 framework, since after updating from dnx to dotnet, I have seen these diamonds occassionally on web-screen...

Just wondering how to solve this. 

With v-grid I can download header texts from server and it will fix this now, or build original strings as charactercode by charactercode to new string, but, wondering, where is the real cure for this. Who knows...

**Comment by JOKaija** [comment]
Solution for non utf-8 encoding problems!!!

https://vlasovstudio.com/fix-file-encoding/
