### ISSUE TITLE
Another problem with spaces!

### ISSUE THREAD

**Issue by JOKaija** [aurelia-ui-toolkits/aurelia-v-grid#62]
{colField:"Uuden tilausnro"},

Will show only "Uuden" on column...

**Comment by vegarringdal** [comment]
Guessing you are referring to the header ? 
Try this if you have spaces in header name:
{colField:"Uuden tilausnro", colHeaderName:"Uuden tilausnro"},

btw, I have a new version Im working on here with grouping etc, buggy:

https://github.com/vegarringdal/vGrid
https://vegarringdal.github.io/vGridDemo/ <- very simple demo
https://www.gitbook.com/book/vegarringdal/dev-rebuild/details <- docs for the new one
