### ISSUE TITLE
This isn't a real issue, but: How to add filter with predefined dropdown variables...

### ISSUE THREAD

**Issue by JOKaija** [aurelia-ui-toolkits/aurelia-v-grid#63]
Couldn't find with rapid search from documentation.

So. How to make dropdown menu on js side for filter. 

Also, is it possible to get filter "data" from columns with js. I'd like to use that same filter, when I create output table as excell format.

**Comment by vegarringdal** [comment]
This is the menu for setting filters Ive included, new grid one with have more options for custom stuff (when I get more time to work with it)
https://aurelia-ui-toolkits.gitbooks.io/aurelia-v-grid-docs/content/chap04/v-header-menu.html

You can get rows displayed in the grid by using this... not at my computer atm
myGrid = {}; //v-grid-context.bind="myGrid"  in <vgrid>
var rows= this.myGrid.ctx.vGridCollectionFiltered;

**Comment by JOKaija** [comment]
I don't want filtered rows... I need only words & values on filter(s), since I pass them to server, which will create an excell file with filters data and stream it to user.

client filterdata -> server excell creation with filters -> server streams excell to client -> client can open it with excell....

Hmmmm..... I COULD use filtered rows, if I strip row IDs and make a List<ID> on client side and send that list to server (= datastream small enough)... So, this is not so hard to change...

**Comment by vegarringdal** [comment]
k, try this:
let filterObj = this.myGrid.ctx.vGridFilter.lastFilter;

**Comment by JOKaija** [comment]
Thank you. Again! :-)
