### ISSUE TITLE
Coloring multiple values on same line

### ISSUE THREAD

**Issue by JOKaija** [aurelia-ui-toolkits/aurelia-v-grid#64]
I got your simple way to color value, if it was > 100 from Gistrun example.
Ok. no problem, it works fine with my text compare method also.

BUT! I have a multiple values on same row, which should have their independent
colors. How I can pass color for them, since tempRef holds only one coloring...

**Comment by JOKaija** [comment]
Oh, sorry, that was easy to solve....

Forget....

**Comment by vegarringdal** [comment]
:+1: 

Did you try the new one Im trying to make ?

You are just feeding the grid with array data, or do you use the paging ?

**Comment by JOKaija** [comment]
No I didn't. Link for it? (I must miss it...)

**Comment by vegarringdal** [comment]
only used cli last tried but I use jspm when developing, Ill do a new test later today and update how to install if it doesnt work

**Comment by vegarringdal** [comment]
there is a demo link where u can see how new one works with locked column, menus etc

**Comment by vegarringdal** [comment]
>No I didn't. Link for it? (I must miss it...)
Naah. Found it. Since it's not jspm installable, I would not install it.
I had a way too much problems with all repos earlier and had to
retrieve my app several times from backup to get everything work again.

I just follow this and new one worked just fine with jspm
https://vegarringdal.gitbooks.io/dev-rebuild/content/chap15/jspm.html

**Comment by JOKaija** [comment]
system.src.js:122 Uncaught (in promise) Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5000/jspm_packages/github/vegarringdal/vGrid@dev-rebuild.html

**Comment by JOKaija** [comment]
How about that filter value setting by .js?

It is mandatory. Then I can release this version and my boss (my nightmare) will be happy for a while... :-)

**Comment by vegarringdal** [comment]
Did you install by using 

```jspm install aurelia-v-grid=github:vegarringdal/vGrid```

I just tested it today

> How about that filter value setting by .js?

Running filter by code and updating the filter inputs?

**Comment by JOKaija** [comment]
Yes I did.

> Running filter by code and updating the filter inputs?

I will if I ever know how.... I'm a little busy too and I it is a big work to re-engineer your code
to get in... You told me how to get filters form v-grid, but that same method vice-versa doesn't work.
And I need somehow to trigger your filter routine too after setting new filter values...

**Comment by JOKaija** [comment]
Hmmm. Did you remove original 0.2.6 before installing vGrid version?

**Comment by vegarringdal** [comment]
yes, they have the same name, would make a copy of you solution and experiment
maybe you hate the new one :-)

**Comment by JOKaija** [comment]
Just installed original back without any uninstallings :-) Works just fine.

But now I try to uninstall the original and try again with new one....

**Comment by JOKaija** [comment]
No, it doesn't find html file... should there be an one?

system.src.js:1051 GET http://localhost:5000/jspm_packages/github/vegarringdal/vGrid@dev-rebuild.html 404 (Not Found)
G @ system.src.js:1051
(anonymous) @ system.src.js:1778
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2802
(anonymous) @ system.src.js:3380
(anonymous) @ system.src.js:3694
(anonymous) @ system.src.js:4086
(anonymous) @ system.src.js:4549
(anonymous) @ system.src.js:4819
(anonymous) @ system.src.js:407
Promise.resolve (async)
m @ system.src.js:676
(anonymous) @ system.src.js:485
Promise.resolve (async)
(anonymous) @ system.src.js:3388
(anonymous) @ system.src.js:3540
(anonymous) @ system.src.js:4588
(anonymous) @ system.src.js:4973
(anonymous) @ system.src.js:422
Promise.resolve (async)
a @ system.src.js:1006
G.i.onreadystatechange @ system.src.js:1027
XMLHttpRequest.send (async)
G @ system.src.js:1051
(anonymous) @ system.src.js:1778
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2802
(anonymous) @ system.src.js:3380
(anonymous) @ system.src.js:3694
(anonymous) @ system.src.js:4086
(anonymous) @ system.src.js:4549
(anonymous) @ system.src.js:4819
(anonymous) @ system.src.js:407
system.src.js:122 Uncaught (in promise) Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5000/jspm_packages/github/vegarringdal/vGrid@dev-rebuild.html
	Error: XHR error (404 Not Found) loading http://localhost:5000/jspm_packages/github/vegarringdal/vGrid@dev-rebuild.html
	Error loading http://localhost:5000/jspm_packages/github/vegarringdal/vGrid@dev-rebuild.h…l!http://localhost:5000/jspm_packages/github/systemjs/plugin-text@0.0.3.js
	Error loading http://localhost:5000/jspm_packages/github/vegarringdal/vGrid@dev-rebuild.html!template-registry-entry

**Comment by JOKaija** [comment]
Easy to switch. Each pakkage will delete the original one, so there is only one package files.... or not ;-)

**Comment by vegarringdal** [comment]
So now it works, I have noe idea what those errors you got where

Haveto go to bed soon, work i 7 hours, but have stared to look at setting values to filter inputs in the new one

I would have preferred to make more advance filter, but it will take a while to make something like that right, so figured could start with something simple for now

Im guessing you want to set filter to use when grid loads, and you also want the inputs to have the values of the filter that you just ran by code

**Comment by JOKaija** [comment]
> Im guessing you want to set filter to use when grid loads, and you also want the inputs to have the values of the filter that you just ran by code

Yep. That is mandatory. Thanks goes to stupid users.... they won't learn ever how to filter... :-)

**Comment by JOKaija** [comment]
And no, the vGrid doesn't work... But changing back to 0.2.6 is easy enough :-)

**Comment by vegarringdal** [comment]
> And no, the vGrid doesn't work.

Ill do a new install tomorrow, incase I broke something when adding features today/cleaning up
Could you do me a favor and install it in a clean skeleton:
https://github.com/aurelia/skeleton-navigation/releases

So I know if its your skeleton or something else, what jspm version, what node/npm ?
@Thanood JSPM master ✨  Do you know any of the errors hes getting ?


----

**About setting filter**


Here is what Ive been able to do in code Im experimenting with in the new grid since last comment...
Adding some features will happend here :-)

> my button code

```
public filterByCode(){
    this.ds.query([{attribute:"country", operator:"*", value:"and"}])
    this.gridConnector.raiseEvent("filterUpdateValues")
  }
````

result:

![test](https://cloud.githubusercontent.com/assets/2901416/21910838/1b2c13b6-d91e-11e6-8062-b6d2cc5d97f6.gif)

**Comment by vegarringdal** [comment]
Did a between test with the new code I added
filter was success, input is kinda useless, but here you could add button using the custom html part for just that column, as a workaround until I make something better built in...

```
this.ds.query([{attribute:"index", operator:">", value:5}, {attribute:"index", operator:"<", value:10}])
this.gridConnector.raiseEvent("filterUpdateValues")
```

![test](https://cloud.githubusercontent.com/assets/2901416/21911249/393b6328-d920-11e6-95f4-53ef8b074bf9.gif)

**Comment by vegarringdal** [comment]
well Im of to bed now, hope we figure out why that install is failing

**Comment by Thanood** [comment]
> Do you know any of the errors hes getting ?

Maybe.. Try to remove the jspm forks you mentioned here: https://github.com/aurelia-ui-toolkits/aurelia-v-grid/issues/64#issuecomment-272291497

All kinds of nastiness can happen when jspm installs "forks" (two versions of the same package at the same time). And that nastiness usually comes in the form of `404` errors first. 😉 

`jspm resolve --only registry:package@version`

so f.i. you had a fork with aurelia-logging:
`jspm resolve --only npm:aurelia-logging@1.2.0`

(see also https://github.com/jspm/jspm-cli/blob/master/docs/installing-packages.md#resolving-conflicts)

off topic: nice, 2.0 beta packages 😃

**Comment by JOKaija** [comment]
Great work!!! I'll salut you!

About my  software version:

NPM: 3.8.3
DOTNET: 1.0.1
NodeJS: 5.10.1

I can create clean app for testing if necessary, but it means, we have to work over weekend. 
I just haven't enough time at work week :-(

I will continue with these conversations at your vGrid -site...
