### ISSUE TITLE
Not on real Issue, but... Real OnDraw event + double filtering to get -between- filter...

### ISSUE THREAD

**Issue by JOKaija** [aurelia-ui-toolkits/aurelia-v-grid#65]
I got the grid working superb!

But...

I need to swap cell text on grid on ondraw function.

If I do something like this:

if (data.tempRef.Id == 2323) data.rowRef.Explanation="this is wrong work";

Cell value changes as it should be, BUT the original data changes too, and this is not what I want,
since data will be transferred to server later on.

Is it only workaround to make duplicate from my original data and use it for grid to keep original
data safe? Brb.... Data table size is 1mb now and will grow up rapidly... (Noonoonoo, I can't split it, based on its usage)!

What I (and other folks too, I think) need, is real ondraw event, where I can change the visible part only (too,) and original data remains. (like when I want to show True/False text based on data on borlands c++/delphi ondraw events on grids etc...)

Maybe we need an one new variable showRef? :)

-----------

Another thing. Double filtering. Should be possible to use two filters on same column. I need ability to filter values and dates -between- method.

Is there somewhere a conversation site about v-grid where I can put my wishes?

**Comment by vegarringdal** [comment]
First issue, display data

if (data.tempRef.Id == 2323) data.tempRef.Explanation="this is wrong work";
col-field="tempRef.Explanation"

**Comment by vegarringdal** [comment]
2 issue:
Another thing. Double filtering. Should be possible to use two filters on same column. I need ability to filter values and dates -between- method.

No real good way to solve this atm, but something worth thinking about on the new grid Im working on when I have time.

What about when you get data from the server and just add a extra column with duplicated data?

How large is the data you are getting from the server btw, rows/columns?

**Comment by JOKaija** [comment]
I get currently about 3000 rows. It will grow 50-100 / month. Can't even figure, what it will be at year 2020.

In some point I have to split/double-buffer data on server side depending rows / page & page number. But currently my big Boss want see ALL data in one page without any pagings / server side double buffering...

So, the boss gets what he wants... :-)

**Comment by vegarringdal** [comment]
> So, the boss gets what he wants... :-)

:+1:  keeping the boss happy is the way to go

You should consider looking at the new grid since you are loading all the data, here you will be able to come with new feature requests since its the one Im developing on

New one have option for locked columns and grouping how it works not.
Its not perfect, some parts isnt 100%, and not everything is the same with how you do stuff, but will give you a lot more options in the long run if you like my grid and want to continue to use it.

@Thanood been using a a bit, looks like hes happy for now

Dont want many users on it, since Im doing sometimes breaking changes if it improves the usage, but having 2 people use it I should go fine.

**Comment by JOKaija** [comment]
I can live with current version, but I know, my boss start to whine, when all previous -between- and drop down features are gone with my new rec-app version. But I really like to use your work, since I had a HUGE problem to get headers & data tables on same size with pure html and css. And kendo (and its table system) will broke my app totally. Now one knows why...

But, now I have to go on. So, how I can setup initial values for filters. Let's say, that I want "Ready" string to "TargetCondition_s" column?
