### ISSUE TITLE
Grayed filter text in english

### ISSUE THREAD

**Issue by JOKaija** [aurelia-ui-toolkits/aurelia-v-grid#66]
Those grayed texts on filter boxes won't follow my own language settings with
v-language.bind=Lang_Fi.

When right clicking, they are what I want.

Any idea, when you have time to implement dropdown filter.
So, when left klicking, you get list of "own filter strings" and use
them instantly. And a new filter option ---> between <---

Something like this as column definitions on .js side for dropdown... (left click!):

stringObject =["valmis","kesken","ei tarvita"]; // in english btw: Ready, not ready and not needed ;-)
{colField:"ReclamationInstructions_s", colDropDownFilter: stringObject}

How about filtering -between- like this ie.: 10-100 or with dates 22.1.2016-22.1.2017.
So, your code would separate edgevalues (including) by splitting variables with "-" character....

Should be easy implementations, when done this way? I could do those to your code
too, but in future, while updating with jspm, I will run BIG PROBLEMS...

When you get those ready, even by special build for me, I will salut 
you and it is a slight chance (depending my bank account) to get donations too ;-)

rgds:
Jari Kaija
jari.kaija@live.com
![vgrid-version-of-page](https://cloud.githubusercontent.com/assets/18458962/21886082/ecd067f2-d8c2-11e6-9ed7-c8a144900330.jpg)

**Comment by vegarringdal** [comment]
> Those grayed texts on filter boxes won't follow my own language settings

Another thing fix in the new grid thanks to @Thanood and his testing :-)
Ill rather use the spare time I have on improving that one.
