### ISSUE TITLE
Freezes, when filtering data what contains nulls

### ISSUE THREAD

**Issue by JOKaija** [aurelia-ui-toolkits/aurelia-v-grid#67]
Yep. Just noticed...

When reading data from servers, there is a BIG chance to get also null
variables. Usually strings. (DateTime and numbers are a quite safe).

So, when reading normal data to v-grid and you have some missing
strings = null in some data cells, v-grid can't handle them and freezes
when trying filter that kind of column.

I had to do iterator to my server side for looping all datacells and if they
were typed as strings: if(xxx == null) xxx = "";

Slow.....

**Comment by Thanood** [comment]
Would a valueConverter be faster?

**Comment by vegarringdal** [comment]
Missing string values or the actual attribute in object ?

**Comment by JOKaija** [comment]
just pure null, without anything. I can recreate error.... take a moment

**Comment by vegarringdal** [comment]
I see the erro in new grid too
Ill do a fix there first, main issue with this is how to deal with them
is it string then "", is it number 0, date is any... I dont have any way of defining schema... maybe I should add something like that in the new grid, or atleast add option for types on columns so it knows how to handle data

new one have replaceable datasource/gridconnector so user can make own/copy mine and improve just that part without updating the grid

I should really add advanced filter for blanks/null in filtering in the new one, the advanced filter @Thanood suggestion in the experimental repo sounds cool (no idea how to do it yet though)

**Comment by JOKaija** [comment]
Defining variables inside:

  {colField:"Id", colHeaderName:"Id", colType:"number"

Will be fine. You can even reuse that colType :-)

**Comment by JOKaija** [comment]
How about colInitialFilter:"Ready",  ;-)

**Comment by vegarringdal** [comment]
>  colType:"number"

something like that, but most new stuff will be added to the new grid, Im pretty much adding/fixing stuff there every week, its typescript so it helps keeping bugs away, and code isnt that much spaghetti like old is where I did 3 rebuild while learing more about aurelia how to even make a plugin 😂
